name: Build npm release

jobs:
  - template: .ci/build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-16.04

  - template: .ci/build-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-10.13

  - template: .ci/build-platform.yml
    parameters:
      platform: Windows
      vmImage: vs2017-win2016

  # This job is kept here as we want to have the platform names in the same file
  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
      - Windows
    pool:
      vmImage: macOS-10.13
      demands: node.js
    steps:
      - template: .ci/cross-release.yml

