version: 2.1

aliases:
  - &opam_env
    TERM: dumb
    OPAMYES: true
orbs:
  win: circleci/windows@2.2.0

  opam_windows:
    commands:
      install:
        steps:
          - run:
              name: Install dependencies
              command: |
                choco install --no-progress cygwin
                if (-not $?) { throw "Failed to install cygwin" }
                choco install --no-progress rsync patch diffutils curl make zip unzip git m4 perl mingw64-x86_64-gcc-core --source=cygwin
                if (-not $?) { throw "Failed to install deps from cygwin" }
          - run:
              name: Install opam
              command: |
                $install_dir = "$Env:TEMP\flow\opam_installer"
                New-Item -ItemType Directory $install_dir
                echo "Downloading opam64.tar.xz"
                (New-Object System.Net.WebClient).DownloadFile("https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/opam64.tar.xz", "$install_dir\opam64.tar.xz")
                echo "Extracting opam64.tar.xz"
                $out_dir = "$install_dir".Replace("\", "/")
                C:\tools\cygwin\bin\tar.exe -x --force-local -f $install_dir\opam64.tar.xz -C "$out_dir"
                echo "Installing opam"
                C:\tools\cygwin\bin\bash.exe -l "$install_dir\opam64\install.sh"
                echo "Done"
      init:
        steps:
          - run:
              name: Init opam
              shell: C:/tools/cygwin/bin/bash.exe --noprofile --norc -eo pipefail
              command: |
                export PATH=$PATH:/usr/local/bin:/usr/bin
                [ -d ~/.opam ] || opam init default 'https://github.com/fdopen/opam-repository-mingw.git#opam2' --bare --disable-sandboxing
      create_switch:
        steps:
          - run:
              name: Create opam switch
              shell: C:/tools/cygwin/bin/bash.exe --noprofile --norc -eo pipefail
              environment:
                PATH: /usr/local/bin:/usr/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0
              command: |
                [ -d _opam ] || opam switch create . ocaml-variants.4.06.1+mingw64c --deps-only --yes -vvv

executors:
  linux-opam:
    docker:
      - image: ocaml/opam2:debian-9
        environment:
          <<: *opam_env
    working_directory: ~/repo
  linux-node:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
  mac:
    macos:
      xcode: "11.4.0"
    environment:
      <<: *opam_env
      OPAM_VERSION: 2.0.5
    working_directory: ~/repo

commands:
  restore-opam-cache:
    steps:
      #- run:
          #name: Create cache breaker
          #command: |
            #echo "ocaml-4.06.1" > .circleci/opamcachebreaker
            #opam --version >> .circleci/opamcachebreaker
            #cat gentype.opam >> .circleci/opamcachebreaker
            #cat package-lock.json >> .circleci/opamcachebreaker
            #cat .circleci/config.yml >> .circleci/opamcachebreaker
      - restore_cache:
          keys:
          #- v1-opam-cache-{{ arch }}-{{ checksum ".circleci/opamcachebreaker" }}
          - v1-opam-cache-{{ arch }}-v0

  save-opam-cache:
    steps:
      - save_cache:
          #key: v1-opam-cache-{{ arch }}-{{ checksum ".circleci/opamcachebreaker" }}
          key: v1-opam-cache-{{ arch }}-v0
          paths:
            - ~/.opam
            - _opam

  create-opam-switch:
    steps:
      - run:
          name: Install deps from opam
          command: |
            eval $(opam env)
            if [ ! -d _opam ]; then
              opam switch create . 4.06.1 --deps-only | cat
            fi
            opam env >> $BASH_ENV
            
jobs:
  build_linux:
    executor: linux-opam

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/artifacts
      - run:
          # installs LTS v12 `node`, `npm`, `zip` and `m4` 
          name: Install debian deps
          command: |
            sudo apt-get update
            sudo apt-get --yes install zip m4 curl software-properties-common
            curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
            sudo apt-get --yes install nodejs
      - restore-opam-cache
      - run:
          name: Update opam repo
          command: |
            opam remote list -s | grep upstream >/dev/null || \
              opam remote add upstream https://opam.ocaml.org --all-switches --set-default | cat
            opam update | cat
      - create-opam-switch
      - run:
          name: Install opam dev dependencies
          command: |
            opam install reason.3.6.0 dune.1.11.4 ocaml-migrate-parsetree.1.3.1 ppx_tools_versioned uri --yes | cat
      - save-opam-cache
      - run:
          name: Build
          command: |
            echo $PATH
            dune build
      - run:
          name: Test
          command: ./_build/default/src/Bin.exe --help 
      - run:
          name: Create tar file for executable
          command: |
            cp _build/default/src/Bin.exe bin.exe
            tar -czvf artifacts/bin-linux.tgz bin.exe
      - store_artifacts:
          path: artifacts/bin-linux.tgz
          destination: bin-linux.tgz
      - persist_to_workspace:
          root: artifacts
          paths:
            - bin-linux.tgz

  build_macos:
    executor: mac

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/artifacts
      - run:
          name: Install opam
          command: |
            if ! [ -x "$(command -v opam)" ]; then
              TMP=${TMPDIR:-/tmp}
              curl -sL -o "$TMP/opam" "https://github.com/ocaml/opam/releases/download/$OPAM_VERSION/opam-$OPAM_VERSION-x86_64-macos"
              install -m 755 "$TMP/opam" "/usr/local/bin/opam"
              rm -f "$TMP/opam"
            fi
      - restore-opam-cache
      - run:
          name: Init opam
          command: |
            [ -d ~/.opam ] || opam init --bare --disable-sandboxing
      - create-opam-switch
      - run:
          name: Install opam dev dependencies
          command: |
            opam install reason.3.6.0 dune.1.11.4 ocaml-migrate-parsetree.1.3.1 ppx_tools_versioned uri --yes | cat
      - save-opam-cache
      - run:
          name: Build
          command: |
            dune build
      - run:
          name: Test
          command: ./_build/default/src/Bin.exe --help 
      - run:
          name: Create tar file for executable
          command: |
            cp _build/default/src/Bin.exe bin.exe
            tar -czvf artifacts/bin-darwin.tgz bin.exe
      - store_artifacts:
          path: artifacts/bin-darwin.tgz
          destination: bin-darwin.tgz
      - persist_to_workspace:
          root: artifacts
          paths:
            - bin-darwin.tgz
  build_win:
    executor: win/default
    environment:
      - REPO_TMP_DIR: 'C:\tmp\repo'
      - OPAMDOWNLOADJOBS: 1
    steps:
      - checkout
      - run:
          name: Set up workspace
          command: |
            New-Item -ItemType Directory $Env:REPO_TMP_DIR
      - opam_windows/install
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Check node / npm version
          shell: C:/tools/cygwin/bin/bash.exe --noprofile --norc -eo pipefail
          environment:
            PATH: /cygdrive/c/Program Files/nodejs:/usr/local/bin:/usr/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0
          command: |
            pwd
            ls -l
            echo "Versions"
            node --version
            npm --version
      - restore_cache:
          keys:
          - v0-opam-cache-{{ arch }}
      - opam_windows/init
      - opam_windows/create_switch
      - run:
          name: Install opam dev dependencies
          shell: C:/tools/cygwin/bin/bash.exe --noprofile --norc -eo pipefail
          environment:
            PATH: /cygdrive/c/Program Files/nodejs:/usr/local/bin:/usr/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0
          command: |
            eval $(opam env)
            opam install reason.3.6.0 dune.1.11.4 ocaml-migrate-parsetree.1.3.1 ppx_tools_versioned uri --yes | cat
      - save_cache:
          #key: opam-cache-{{ arch }}-{{ checksum "C:/tmp/repo/opamcachebreaker" }}
          key: v0-opam-cache-{{ arch }}
          paths:
            - C:/tools/cygwin/home/circleci/.opam
            - _opam
      - run:
          name: Build & Test
          shell: C:/tools/cygwin/bin/bash.exe --noprofile --norc -eo pipefail
          environment:
            PATH: /cygdrive/c/Program Files/nodejs:/usr/local/bin:/usr/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0
          command: |
             eval $(opam env)
             dune build
             ./_build/default/src/Bin.exe --help
      - run:
          name: Create tar file for executable
          command: |
            cp _build/default/src/Bin.exe bin.exe
            tar -czvf artifacts/bin-win32.tgz bin.exe
      - store_artifacts:
          path: artifacts/bin-win32.tgz
          destination: bin-win32.tgz
      - persist_to_workspace:
          root: artifacts
          paths:
            - bin-win32.tgz
  artifacts:
    executor: linux-node
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/artifacts
      - run:
          name: Pack genType
          command: |
            cd artifacts
            mkdir linux
            tar -xf bin-linux.tgz -C linux
            mkdir win32
            tar -xf bin-win32.tgz -C win32
            mkdir darwin
            tar -xf bin-darwin.tgz -C darwin

            # Pack everything up
            tar -czvf binaries.tgz linux win32 darwin
      - store_artifacts:
          path: artifacts/binaries.tgz
          destination: binaries.tgz
      - persist_to_workspace:
          root: artifacts
          paths:
            - binaries.tgz
workflows:
  version: 2
  build_deploy:
    jobs:
      - build_linux:
          filters:
            tags:
              only: /.*/
      - build_macos:
          filters:
            tags:
              only: /.*/
      - build_win:
          filters:
            tags:
              only: /.*/
      - artifacts:
          requires:
            - build_linux
            - build_win
            - build_macos
          filters:
            tags:
              only: /.*/
